module.exports = Object.freeze({
    SKILL_NAME: 'Philly Rails',
    LIST_OF_STATIONS: ['30th Street Station',
'49th St',
'9th St',
'Airport Terminal A',
'Airport Terminal B',
'Airport Terminals C & D',
'Airport Terminals E & F',
'Allegheny',
'Allen Lane',
'Ambler',
'Angora',
'Ardmore',
'Ardsley',
'Bala',
'Berwyn',
'Bethayres',
'Bridesburg',
'Bristol',
'Bryn Mawr',
'Carpenter',
'Chalfont',
'Chelten Avenue',
'Cheltenham',
'Chester Transportation Center',
'Chestnut Hill East',
'Chestnut Hill West',
'Churchmans Crossing',
'Claymont',
'Clifton–Aldan',
'Colmar',
'Conshohocken',
'Cornwells Heights',
'Crestmont',
'Croydon',
'Crum Lynne',
'Curtis Park',
'Cynwyd',
'Darby',
'Daylesford',
'Delaware Valley College',
'Devon',
'Downingtown',
'Doylestown',
'East Falls',
'Eastwick',
'Eddington',
'Eddystone',
'Elkins Park',
'Elm Street, Norristown',
'Elwyn',
'Exton',
'Fern Rock Transportation Center',
'Fernwood–Yeadon',
'Folcroft',
'Forest Hills',
'Fort Washington',
'Fortuna',
'Fox Chase',
'Germantown',
'Gladstone',
'Glenolden',
'Glenside',
'Gravers',
'Gwynedd Valley',
'Hatboro',
'Haverford',
'Highland',
'Highland Avenue',
'Holmesburg Junction',
'Ivy Ridge',
'Jefferson Station',
'Jenkintown–Wyncote',
'Langhorne',
'Lansdale',
'Lansdowne',
'Lawndale',
'Levittown',
'Link Belt',
'Main Street, Norristown',
'Malvern',
'Manayunk',
'Marcus Hook',
'Meadowbrook',
'Media',
'Melrose Park',
'Merion',
'Miquon',
'Morton',
'Mount Airy',
'Moylan – Rose Valley',
'Narberth',
'Neshaminy Falls',
'New Britain',
'Newark',
'Noble',
'Norristown Transportation Center',
'North Broad',
'North Hills',
'North Philadelphia',
'North Wales',
'Norwood',
'Olney',
'Oreland',
'Overbrook',
'Paoli',
'Penllyn',
'Pennbrook',
'Philmont',
'Primos',
'Prospect Park',
'Queen Lane',
'Radnor',
'Ridley Park',
'Rosemont',
'Roslyn',
'Rydal',
'Ryers',
'Secane',
'Sedgwick',
'Sharon Hill',
'Somerton',
'Spring Mill',
'St. Davids',
'St. Martins',
'Stenton',
'Strafford',
'Suburban Station',
'Swarthmore',
'Tacony',
'Temple University',
'Thorndale',
'Torresdale',
'Trenton Transit Center',
'Trevose',
'Tulpehocken',
'University City',
'Upsal',
'Villanova',
'Wallingford',
'Warminster',
'Washington Lane',
'Wayne',
'Wayne Junction',
'West Trenton',
'Whitford',
'Willow Grove',
'Wilmington',
'Wissahickon',
'Wister',
'Woodbourne',
'Wyndmoor',
'Wynnefield Avenue',
'Wynnewood',
'Yardley']
});